import { Metadata } from "next";
import { Nanum_Pen_Script, Anton } from "next/font/google";
import localFont from "next/font/local";

export const doldam = localFont({
  src: [
    {
      path: "../asset/fonts/doldam.woff2",
    },
    {
      path: "../asset/fonts/doldam.woff",
    },
  ],
});

export const nanumPenScript = Nanum_Pen_Script({ weight: "400" });
export const anton = Anton({ weight: "400" });

export const metadata: Metadata = {
  title: { template: "%s | SU", default: "Next.JS | SU" },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
